version: '2.0'

services:
    api:
        container_name: nest_api
        build: .
        ports:
            - ${NEST_PORT}:${NEST_PORT}
        volumes:
            - .:/home/api
            - /home/api/node_modules

    database:
        container_name: nest_db
        image: postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: 'root'
            POSTGRES_PASSWORD: '0'
            POSTGRES_DB: 'cyan'
        restart: always
