GET http://localhost:3000/user
//Listar todos os usuários
###

GET http://localhost:3000/user/:email
//Listar um usuário específico
Content-Type: application/json

{
    "email":"bruno@gmail.com"
}
###

POST http://localhost:3000/user
//Criar um usuário
Content-Type: application/json

{
    "name": "Jeremias",
    "email": "jere@gmail.com"
}
###

PATCH http://localhost:3000/user
//Atualizar um usuário
Content-Type: application/json

{
    "name": "Teste",
    "email": "teste@gmail.com"
}
###
DELETE http://localhost:3000/user/:email
//Deleta um usuário
Content-Type: application/json

{
    "email": "jere@gmail.com"
}